CREATE DATABASE BookManagement
USE BookManagement

CREATE TABLE Category(
	CategoryID 	VARCHAR(10) PRIMARY KEY,
	CategoryName NVARCHAR(20) NOT NULL,
)

CREATE TABLE Publisher(
	PublisherID	VARCHAR(10) PRIMARY KEY,
	PublisherName NVARCHAR(50) NOT NULL,
	Email NVARCHAR(50),
	[Address] NVARCHAR(100),
	Phone VARCHAR(20),
	[Image] VARCHAR(MAX)
)
CREATE TABLE Book(
	ISBN VARCHAR(20) PRIMARY KEY,
	Title NVARCHAR(100) NOT NULL,
	Author NVARCHAR(50),
	Price Decimal(2,0) NOT NULL DEFAULT 0,
	Brief NVARCHAR(MAX),
	[Status] BIT NOT NULL DEFAULT 0,
	[Description] NVARCHAR(MAX),
	[Image] VARCHAR(MAX),
	CategoryID VARCHAR(10),
	PublisherID VARCHAR(10),
	FOREIGN KEY(CategoryID) REFERENCES dbo.Category(CategoryId)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	FOREIGN KEY(PublisherID) REFERENCES dbo.Publisher(PublisherID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
)

CREATE TABLE Role(
	RoleID VARCHAR(10) PRIMARY KEY,
	RoleName NVARCHAR(20),
	[Description] NVARCHAR(50)
)
CREATE TABLE [User](
	UserID VARCHAR(10) PRIMARY KEY,
	FullName NVARCHAR(50) NOT NULL,
	Phone VARCHAR(20),
	[Address] NVARCHAR(50),
	Username VARCHAR(20) NOT NULL,
	[Password] VARCHAR(20) NOT NULL,
	[Status] BIT NOT NULL DEFAULT 0,
	[Image] VARCHAR(MAX),
	RoleID VARCHAR(10) NOT NULL,
	FOREIGN KEY(RoleID) REFERENCES dbo.Role(RoleID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
)

CREATE TABLE [Order](
	OrderID VARCHAR(10) PRIMARY KEY,
	[Description] NVARCHAR(MAX),
	Total NVARCHAR(50),
	CreateDate DATE NOT NULL,
	UserID VARCHAR(10),
	Amount Decimal(2,0),
	FOREIGN KEY(UserID) REFERENCES dbo.[User](UserID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
)
CREATE TABLE OrderDetail(
	OrderDetailID VARCHAR(10) PRIMARY KEY,
	Quantity INT NOT NULL,
	Price Decimal(2,0) NOT NULL,
	OrderID VARCHAR(10),
	BookID VARCHAR(20),
	FOREIGN KEY(OrderID) REFERENCES dbo.[Order](OrderID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	FOREIGN KEY(BookID) REFERENCES dbo.[Book](ISBN)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
)