/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.softech.bookmanagement.form;

/**
 *
 * @author Nguyen Bae
 */
public class Form_CatAndPub extends javax.swing.JPanel {

    /**
     * Creates new form Form_CatAndPub
     */
    public Form_CatAndPub() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JLayeredPane();
        txtCategory = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAddCat = new keeptoo.KButton();
        btnDeleteCat = new keeptoo.KButton();
        btnUpdateCat = new keeptoo.KButton();
        panelBorder1 = new com.softech.bookmanagement.swing.PanelBorder();
        jLabel1 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        tblCategory = new com.softech.bookmanagement.swing.Table();
        spTable1 = new javax.swing.JScrollPane();
        tblPublisher = new com.softech.bookmanagement.swing.Table();
        panel2 = new javax.swing.JLayeredPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPublisherPhone = new javax.swing.JTextField();
        txtPublisherName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPublisherAddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPublisherEmail = new javax.swing.JTextField();
        panel3 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        btnUpdatePub = new keeptoo.KButton();
        btnDeletePub = new keeptoo.KButton();
        jButton1 = new javax.swing.JButton();
        btnAddPub = new keeptoo.KButton();

        setBackground(new java.awt.Color(242, 242, 242));
        setPreferredSize(new java.awt.Dimension(919, 620));

        panel.setPreferredSize(new java.awt.Dimension(279, 252));
        panel.setRequestFocusEnabled(false);

        txtCategory.setBackground(new java.awt.Color(242, 242, 242));
        txtCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCategory.setToolTipText("");
        txtCategory.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(63, 43, 150)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(63, 43, 150));
        jLabel3.setText("Category Name");

        btnAddCat.setText("ADD");
        btnAddCat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddCat.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAddCat.setkEndColor(new java.awt.Color(168, 192, 255));
        btnAddCat.setkHoverEndColor(new java.awt.Color(63, 43, 150));
        btnAddCat.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAddCat.setkHoverStartColor(new java.awt.Color(168, 192, 255));
        btnAddCat.setkStartColor(new java.awt.Color(63, 43, 150));

        btnDeleteCat.setText("DELETE");
        btnDeleteCat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteCat.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnDeleteCat.setkEndColor(new java.awt.Color(168, 192, 255));
        btnDeleteCat.setkHoverEndColor(new java.awt.Color(63, 43, 150));
        btnDeleteCat.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDeleteCat.setkHoverStartColor(new java.awt.Color(168, 192, 255));
        btnDeleteCat.setkStartColor(new java.awt.Color(63, 43, 150));

        btnUpdateCat.setText("UPDATE");
        btnUpdateCat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateCat.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnUpdateCat.setkEndColor(new java.awt.Color(168, 192, 255));
        btnUpdateCat.setkHoverEndColor(new java.awt.Color(63, 43, 150));
        btnUpdateCat.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUpdateCat.setkHoverStartColor(new java.awt.Color(168, 192, 255));
        btnUpdateCat.setkStartColor(new java.awt.Color(63, 43, 150));

        panel.setLayer(txtCategory, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(btnAddCat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(btnDeleteCat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(btnUpdateCat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCategory)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnAddCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteCat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(btnUpdateCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddCat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateCat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteCat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("Category and Publisher Management");

        tblCategory.setBackground(new java.awt.Color(242, 242, 242));
        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category Name"
            }
        ));
        spTable.setViewportView(tblCategory);

        tblPublisher.setBackground(new java.awt.Color(242, 242, 242));
        tblPublisher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Publisher Name", "Publisher Phone", "Publisher Address", "Publisher Email"
            }
        ));
        spTable1.setViewportView(tblPublisher);

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(spTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel2.setPreferredSize(new java.awt.Dimension(278, 282));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(63, 43, 150));
        jLabel6.setText("Publisher Name");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(63, 43, 150));
        jLabel7.setText("Publisher Phone");

        txtPublisherPhone.setBackground(new java.awt.Color(242, 242, 242));
        txtPublisherPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPublisherPhone.setToolTipText("");
        txtPublisherPhone.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(63, 43, 150)));

        txtPublisherName.setBackground(new java.awt.Color(242, 242, 242));
        txtPublisherName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPublisherName.setToolTipText("");
        txtPublisherName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(63, 43, 150)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(63, 43, 150));
        jLabel8.setText("Publisher Address");

        txtPublisherAddress.setBackground(new java.awt.Color(242, 242, 242));
        txtPublisherAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPublisherAddress.setToolTipText("");
        txtPublisherAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(63, 43, 150)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(63, 43, 150));
        jLabel9.setText("Publisher Email");

        txtPublisherEmail.setBackground(new java.awt.Color(242, 242, 242));
        txtPublisherEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPublisherEmail.setToolTipText("");
        txtPublisherEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(63, 43, 150)));

        panel2.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel2.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel2.setLayer(txtPublisherPhone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel2.setLayer(txtPublisherName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel2.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel2.setLayer(txtPublisherAddress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel2.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel2.setLayer(txtPublisherEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPublisherName)
                    .addComponent(txtPublisherPhone)
                    .addComponent(txtPublisherAddress)
                    .addComponent(txtPublisherEmail)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(0, 136, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPublisherName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPublisherPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPublisherAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPublisherEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        panel3.setPreferredSize(new java.awt.Dimension(298, 282));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );

        btnUpdatePub.setText("UPDATE");
        btnUpdatePub.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdatePub.setkEndColor(new java.awt.Color(168, 192, 255));
        btnUpdatePub.setkHoverEndColor(new java.awt.Color(63, 43, 150));
        btnUpdatePub.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnUpdatePub.setkHoverStartColor(new java.awt.Color(168, 192, 255));
        btnUpdatePub.setkStartColor(new java.awt.Color(63, 43, 150));

        btnDeletePub.setText("DELETE");
        btnDeletePub.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeletePub.setkEndColor(new java.awt.Color(168, 192, 255));
        btnDeletePub.setkHoverEndColor(new java.awt.Color(63, 43, 150));
        btnDeletePub.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnDeletePub.setkHoverStartColor(new java.awt.Color(168, 192, 255));
        btnDeletePub.setkStartColor(new java.awt.Color(63, 43, 150));

        jButton1.setText("Choose File");

        btnAddPub.setText("ADD");
        btnAddPub.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddPub.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAddPub.setkEndColor(new java.awt.Color(168, 192, 255));
        btnAddPub.setkHoverEndColor(new java.awt.Color(63, 43, 150));
        btnAddPub.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnAddPub.setkHoverStartColor(new java.awt.Color(168, 192, 255));
        btnAddPub.setkStartColor(new java.awt.Color(63, 43, 150));

        panel3.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel3.setLayer(btnUpdatePub, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel3.setLayer(btnDeletePub, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel3.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel3.setLayer(btnAddPub, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPub, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(btnUpdatePub, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnDeletePub, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(btnAddPub, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdatePub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnDeletePub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnAddCat;
    private keeptoo.KButton btnAddPub;
    private keeptoo.KButton btnDeleteCat;
    private keeptoo.KButton btnDeletePub;
    private keeptoo.KButton btnUpdateCat;
    private keeptoo.KButton btnUpdatePub;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLayeredPane panel;
    private javax.swing.JLayeredPane panel2;
    private javax.swing.JLayeredPane panel3;
    private com.softech.bookmanagement.swing.PanelBorder panelBorder1;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JScrollPane spTable1;
    private com.softech.bookmanagement.swing.Table tblCategory;
    private com.softech.bookmanagement.swing.Table tblPublisher;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtPublisherAddress;
    private javax.swing.JTextField txtPublisherEmail;
    private javax.swing.JTextField txtPublisherName;
    private javax.swing.JTextField txtPublisherPhone;
    // End of variables declaration//GEN-END:variables
}
